name: Update libdrm.spec

on:
  schedule:
    - cron: "0 0 * * *" # Run once per day at midnight
  workflow_dispatch: # Manual trigger

jobs:
  update-spec:
    runs-on: ubuntu-24.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Get latest version from GitLab tags
      run: |
        LATEST_TAG=$(curl -s "https://gitlab.freedesktop.org/api/v4/projects/mesa%2Fdrm/repository/tags" \
        | jq -r '.[0].name' | grep -oP 'libdrm-\K[0-9]+\.[0-9]+\.[0-9]+')
        LIB_VERSION=$(echo $LATEST_TAG | cut -d'.' -f3)
        echo "$LIB_VERSION" > lib_version.txt
        
        # Also get latest commit for shortcommit
        curl -s "https://gitlab.freedesktop.org/api/v4/projects/mesa%2Fdrm/repository/commits" \
        | jq -r '.[0].id' > latest_commit.txt
      env:
        GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}

    - name: Update libdrm.spec
      run: |
        LIB_VERSION=$(cat lib_version.txt)
        COMMIT=$(cat latest_commit.txt)
        SHORTCOMMIT=${COMMIT:0:7}
        
        # Get current values from spec file
        OLD_LIB_VERSION=$(grep -oP '^%global lib_version \K\d+' libdrm.spec)
        OLD_COMMIT=$(grep -oP '^%global commit \K\w+' libdrm.spec)
        
        # Check if anything changed
        if [ "$LIB_VERSION" != "$OLD_LIB_VERSION" ] || [ "$COMMIT" != "$OLD_COMMIT" ]; then
          # Get current subversion number
          CURRENT_SUBVERSION=$(grep -oP 'Version:\s+2\.4\.%\{lib_version\}\.\K\d+' libdrm.spec)
          # Increment subversion
          NEW_SUBVERSION=$((CURRENT_SUBVERSION + 1))
        else
          # No changes, keep current subversion
          NEW_SUBVERSION=$(grep -oP 'Version:\s+2\.4\.%\{lib_version\}\.\K\d+' libdrm.spec)
        fi
        
        # Update spec file
        sed -i "s/^%global lib_version .*/%global lib_version ${LIB_VERSION}/" libdrm.spec
        sed -i "s/^%global commit .*/%global commit ${COMMIT}/" libdrm.spec
        sed -i "s/^%global shortcommit .*/%global shortcommit ${SHORTCOMMIT}/" libdrm.spec
        sed -i "s/Version:\s*2\.4\.%{lib_version}\.[0-9]\+/Version:        2.4.%{lib_version}.${NEW_SUBVERSION}/" libdrm.spec

    - name: Commit and push changes
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add libdrm.spec
        if git diff-index --quiet HEAD; then
          echo "No changes to commit."
        else
          LIB_VERSION=$(cat lib_version.txt)
          COMMIT=$(cat latest_commit.txt)
          git commit -m "Update libdrm.spec to version ${LIB_VERSION} (${COMMIT:0:7})"
          git push origin HEAD:${{ github.ref_name }}
        fi
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Clean up temporary files
      run: rm -f lib_version.txt latest_commit.txt
